name: Code review
about: Request a new code review
title: ''
labels: ''
assignees: ''
body:
  - type: input
    id: project-name
    attributes:
      label: What is the name of your project?
      placeholder: ex. textual
    validations:
      required: true
  - type: input
    id: project-url
    attributes:
      label: What is the url of your project?
      placeholder: ex. https://github.com/willmcgugan/textual
    validations:
      required: true
  - type: textarea
    id: shoulkd-know
    attributes:
      label: Is there anything else I should know about the code?
      placeholder: ""
    validations:
      required: false
  - type: textarea
    id: focus
    attributes:
      label: Are there any areas you would like me to focus on?
      placeholder: ""
    validations:
      required: false
  - type: dropdown
    id: reviewed
    attributes:
      label: Have I reviewed this project previously?
      multiple: true
      options:
        - No
        - Yes
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree for the code review to be public 
      options:
        - label: I agree for the code review to be public
          required: true